site_name: Multi-Indicator Small Area Estimation Resource
site_url: https://sae4lmic.stat.uw.edu
theme:
  name: material
  custom_dir: overrides/landing_page

  features:
  - navigation.indexes
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.tracking
  - navigation.top
  - navigation.instant
  - navigation.instant.progress
  - search.highlight
  - search.share
  - search.suggest

extra:
  analytics:
    provider: google
    property: G-F18NPDHZTE
  hide:
    - toc


nav:
  - Home: index.md
  - Burkina Faso:
    - Overview: country_selection/Burkina Faso/burkina_faso.md
    - Maternal Health:
      - 4+ ANC Visits: country_selection/Burkina Faso/RH_ANCN_W_N4P.md
      - Delivery by Skilled Provider: country_selection/Burkina Faso/RH_DELA_C_SKP.md
      - Delivery in Health Facility: country_selection/Burkina Faso/RH_DELP_C_DHT.md
      - Modern Contraception: country_selection/Burkina Faso/FP_CUSM_W_MOD.md
    - Child Health:
      - DTP 3 coverage: country_selection/Burkina Faso/CH_VACC_C_DP3.md
      - MCV 1 coverage: country_selection/Burkina Faso/CH_VACC_C_MSL.md
      - No Vaccination received: country_selection/Burkina Faso/CH_VACC_C_NON.md
      - Stunting prevalence: country_selection/Burkina Faso/CN_NUTS_C_HA2.md
      - Wasting prevalence: country_selection/Burkina Faso/CN_NUTS_C_WH2.md
      - ITN use under 5: country_selection/Burkina Faso/ML_NETC_C_ITN.md
    - Social Determinants of Health:
      - Mobile phone ownership (women): country_selection/Burkina Faso/CO_MOBB_W_MOB.md
      - Women with secondary or higher education: country_selection/Burkina Faso/ED_EDUC_W_SEH.md
      - Women who are literate: country_selection/Burkina Faso/ED_LITR_W_LIT.md
      - Lowest 2 Wealth Quintiles: country_selection/Burkina Faso/HC_WIXQ_P_12Q.md

  - Congo Democratic Republic:
    - Overview: country_selection/Congo Democratic Republic/congo_democratic_republic.md
    - Maternal Health:
      - 4+ ANC Visits: country_selection/Congo Democratic Republic/RH_ANCN_W_N4P.md
      - Delivery by Skilled Provider: country_selection/Congo Democratic Republic/RH_DELA_C_SKP.md
      - Delivery in Health Facility: country_selection/Congo Democratic Republic/RH_DELP_C_DHT.md
      - Modern Contraception: country_selection/Congo Democratic Republic/FP_CUSM_W_MOD.md
    - Child Health:
      - DTP 3 coverage: country_selection/Congo Democratic Republic/CH_VACC_C_DP3.md
      - MCV 1 coverage: country_selection/Congo Democratic Republic/CH_VACC_C_MSL.md
      - No Vaccination received: country_selection/Congo Democratic Republic/CH_VACC_C_NON.md
      - Stunting prevalence: country_selection/Congo Democratic Republic/CN_NUTS_C_HA2.md
      - Wasting prevalence: country_selection/Congo Democratic Republic/CN_NUTS_C_WH2.md
      - ITN use under 5: country_selection/Congo Democratic Republic/ML_NETC_C_ITN.md
    - Social Determinants of Health:
      - Mobile phone ownership (women): country_selection/Congo Democratic Republic/CO_MOBB_W_MOB.md
      - Women with secondary or higher education: country_selection/Congo Democratic Republic/ED_EDUC_W_SEH.md
      - Women who are literate: country_selection/Congo Democratic Republic/ED_LITR_W_LIT.md
      - Lowest 2 Wealth Quintiles: country_selection/Congo Democratic Republic/HC_WIXQ_P_12Q.md
    
      
  - Ethiopia:
    - Overview: country_selection/Ethiopia/ethiopia.md
    - Maternal Health:
      - 4+ ANC Visits: country_selection/Ethiopia/RH_ANCN_W_N4P.md
      - Delivery by Skilled Provider: country_selection/Ethiopia/RH_DELA_C_SKP.md
      - Delivery in Health Facility: country_selection/Ethiopia/RH_DELP_C_DHT.md
      - Modern Contraception: country_selection/Ethiopia/FP_CUSM_W_MOD.md
    - Child Health:
      - DTP 3 coverage: country_selection/Ethiopia/CH_VACC_C_DP3.md
      - MCV 1 coverage: country_selection/Ethiopia/CH_VACC_C_MSL.md
      - No Vaccination received: country_selection/Ethiopia/CH_VACC_C_NON.md
      - Stunting prevalence: country_selection/Ethiopia/CN_NUTS_C_HA2.md
      - Wasting prevalence: country_selection/Ethiopia/CN_NUTS_C_WH2.md
    - Social Determinants of Health:
      - Women with secondary or higher education: country_selection/Ethiopia/ED_EDUC_W_SEH.md
      - Women who are literate: country_selection/Ethiopia/ED_LITR_W_LIT.md
      - Lowest 2 Wealth Quintiles: country_selection/Ethiopia/HC_WIXQ_P_12Q.md
    
      
  - Kenya:
    - Overview: country_selection/Kenya/kenya.md
    - Maternal Health:
      - 4+ ANC Visits: country_selection/Kenya/RH_ANCN_W_N4P.md
      - Delivery by Skilled Provider: country_selection/Kenya/RH_DELA_C_SKP.md
      - Delivery in Health Facility: country_selection/Kenya/RH_DELP_C_DHT.md
      - Modern Contraception: country_selection/Kenya/FP_CUSM_W_MOD.md
    - Child Health:
      - DTP 3 coverage: country_selection/Kenya/CH_VACC_C_DP3.md
      - MCV 1 coverage: country_selection/Kenya/CH_VACC_C_MSL.md
      - No Vaccination received: country_selection/Kenya/CH_VACC_C_NON.md
      - Stunting prevalence: country_selection/Kenya/CN_NUTS_C_HA2.md
      - Wasting prevalence: country_selection/Kenya/CN_NUTS_C_WH2.md
      - ITN use under 5: country_selection/Kenya/ML_NETC_C_ITN.md
    - Social Determinants of Health:
      - Mobile phone ownership (women): country_selection/Kenya/CO_MOBB_W_MOB.md
      - Women with secondary or higher education: country_selection/Kenya/ED_EDUC_W_SEH.md
      - Women who are literate: country_selection/Kenya/ED_LITR_W_LIT.md
      - Lowest 2 Wealth Quintiles: country_selection/Kenya/HC_WIXQ_P_12Q.md
    
      
  - Mozambique:
    - Overview: country_selection/Mozambique/mozambique.md
    - Maternal Health:
      - 4+ ANC Visits: country_selection/Mozambique/RH_ANCN_W_N4P.md
      - Delivery by Skilled Provider: country_selection/Mozambique/RH_DELA_C_SKP.md
      - Delivery in Health Facility: country_selection/Mozambique/RH_DELP_C_DHT.md
      - Modern Contraception: country_selection/Mozambique/FP_CUSM_W_MOD.md
    - Child Health:
      - DTP 3 coverage: country_selection/Mozambique/CH_VACC_C_DP3.md
      - MCV 1 coverage: country_selection/Mozambique/CH_VACC_C_MSL.md
      - No Vaccination received: country_selection/Mozambique/CH_VACC_C_NON.md
      - Stunting prevalence: country_selection/Mozambique/CN_NUTS_C_HA2.md
      - Wasting prevalence: country_selection/Mozambique/CN_NUTS_C_WH2.md
      - ITN use under 5: country_selection/Mozambique/ML_NETC_C_ITN.md
    - Social Determinants of Health:
      - Mobile phone ownership (women): country_selection/Mozambique/CO_MOBB_W_MOB.md
      - Women with secondary or higher education: country_selection/Mozambique/ED_EDUC_W_SEH.md
      - Women who are literate: country_selection/Mozambique/ED_LITR_W_LIT.md
      - Lowest 2 Wealth Quintiles: country_selection/Mozambique/HC_WIXQ_P_12Q.md
    

  - Nigeria: 
    - Overview: country_selection/Nigeria/nigeria.md
    - Maternal Health:
      - 4+ ANC Visits: country_selection/Nigeria/RH_ANCN_W_N4P.md
      - Delivery by Skilled Provider: country_selection/Nigeria/RH_DELA_C_SKP.md
      - Delivery in Health Facility: country_selection/Nigeria/RH_DELP_C_DHT.md
      - Modern Contraception: country_selection/Nigeria/FP_CUSM_W_MOD.md
    - Child Health:
      - DTP 3 coverage: country_selection/Nigeria/CH_VACC_C_DP3.md
      - MCV 1 coverage: country_selection/Nigeria/CH_VACC_C_MSL.md
      - No Vaccination received: country_selection/Nigeria/CH_VACC_C_NON.md
      - Stunting prevalence: country_selection/Nigeria/CN_NUTS_C_HA2.md
      - Wasting prevalence: country_selection/Nigeria/CN_NUTS_C_WH2.md
      - ITN use under 5: country_selection/Nigeria/ML_NETC_C_ITN.md
    - Social Determinants of Health:
      - Mobile phone ownership (women): country_selection/Nigeria/CO_MOBB_W_MOB.md
      - Women with secondary or higher education: country_selection/Nigeria/ED_EDUC_W_SEH.md
      - Women who are literate: country_selection/Nigeria/ED_LITR_W_LIT.md
      - Lowest 2 Wealth Quintiles: country_selection/Nigeria/HC_WIXQ_P_12Q.md
    
  
  - Rwanda: 
    - Overview: country_selection/Rwanda/rwanda.md
    - Maternal Health:
      - 4+ ANC Visits: country_selection/Rwanda/RH_ANCN_W_N4P.md
      - Delivery by Skilled Provider: country_selection/Rwanda/RH_DELA_C_SKP.md
      - Delivery in Health Facility: country_selection/Rwanda/RH_DELP_C_DHT.md
      - Modern Contraception: country_selection/Rwanda/FP_CUSM_W_MOD.md
    - Child Health:
      - DTP 3 coverage: country_selection/Rwanda/CH_VACC_C_DP3.md
      - MCV 1 coverage: country_selection/Rwanda/CH_VACC_C_MSL.md
      - No Vaccination received: country_selection/Rwanda/CH_VACC_C_NON.md
      - Stunting prevalence: country_selection/Rwanda/CN_NUTS_C_HA2.md
      - Wasting prevalence: country_selection/Rwanda/CN_NUTS_C_WH2.md
      - ITN use under 5: country_selection/Rwanda/ML_NETC_C_ITN.md
    - Social Determinants of Health:
      - Mobile phone ownership (women): country_selection/Rwanda/CO_MOBB_W_MOB.md
      - Women with secondary or higher education: country_selection/Rwanda/ED_EDUC_W_SEH.md
      - Women who are literate: country_selection/Rwanda/ED_LITR_W_LIT.md
      - Lowest 2 Wealth Quintiles: country_selection/Rwanda/HC_WIXQ_P_12Q.md
    
  
  - Senegal:
    - Overview: country_selection/Senegal/senegal.md
    - Maternal Health:
      - 4+ ANC Visits: country_selection/Senegal/RH_ANCN_W_N4P.md
      - Delivery by Skilled Provider: country_selection/Senegal/RH_DELA_C_SKP.md
      - Delivery in Health Facility: country_selection/Senegal/RH_DELP_C_DHT.md
      - Modern Contraception: country_selection/Senegal/FP_CUSM_W_MOD.md
    - Child Health:
      - DTP 3 coverage: country_selection/Senegal/CH_VACC_C_DP3.md
      - MCV 1 coverage: country_selection/Senegal/CH_VACC_C_MSL.md
      - No Vaccination received: country_selection/Senegal/CH_VACC_C_NON.md
      - Stunting prevalence: country_selection/Senegal/CN_NUTS_C_HA2.md
      - Wasting prevalence: country_selection/Senegal/CN_NUTS_C_WH2.md
      - ITN use under 5: country_selection/Senegal/ML_NETC_C_ITN.md
    - Social Determinants of Health:
      - Mobile phone ownership (women): country_selection/Senegal/CO_MOBB_W_MOB.md
      - Women with secondary or higher education: country_selection/Senegal/ED_EDUC_W_SEH.md
      - Women who are literate: country_selection/Senegal/ED_LITR_W_LIT.md
      - Lowest 2 Wealth Quintiles: country_selection/Senegal/HC_WIXQ_P_12Q.md
    
  
  - Tanzania:
    - Overview: country_selection/Tanzania/tanzania.md
    - Maternal Health:
      - 4+ ANC Visits: country_selection/Tanzania/RH_ANCN_W_N4P.md
      - Delivery by Skilled Provider: country_selection/Tanzania/RH_DELA_C_SKP.md
      - Delivery in Health Facility: country_selection/Tanzania/RH_DELP_C_DHT.md
      - Modern Contraception: country_selection/Tanzania/FP_CUSM_W_MOD.md
    - Child Health:
      - DTP 3 coverage: country_selection/Tanzania/CH_VACC_C_DP3.md
      - MCV 1 coverage: country_selection/Tanzania/CH_VACC_C_MSL.md
      - No Vaccination received: country_selection/Tanzania/CH_VACC_C_NON.md
      - Stunting prevalence: country_selection/Tanzania/CN_NUTS_C_HA2.md
      - Wasting prevalence: country_selection/Tanzania/CN_NUTS_C_WH2.md
      - ITN use under 5: country_selection/Tanzania/ML_NETC_C_ITN.md
    - Social Determinants of Health:
      - Mobile phone ownership (women): country_selection/Tanzania/CO_MOBB_W_MOB.md
      - Women with secondary or higher education: country_selection/Tanzania/ED_EDUC_W_SEH.md
      - Women who are literate: country_selection/Tanzania/ED_LITR_W_LIT.md
      - Lowest 2 Wealth Quintiles: country_selection/Tanzania/HC_WIXQ_P_12Q.md
  - More Info:
    - Methodology: add_info/methods.md
    - Indicators: add_info/indicators.md
    
  

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html

extra_css:
  - assets/stylesheets/custom.css
  - overrides/extra.css
  - stylesheets/extra.css