name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Change to 'master' if that's your default branch
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    # Allow only one concurrent deployment
    concurrency:
      group: "pages"
      cancel-in-progress: false
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for git info plugins
        lfs: true  # Check out Git LFS files
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install mkdocs mkdocs-material
        # Install additional plugins if you have a requirements.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Build MkDocs site
      run: mkdocs build --strict
    
    - name: Copy CNAME to site directory
      run: |
        if [ -f CNAME ]; then
          cp CNAME site/
          echo "CNAME file copied to site directory"
          cat site/CNAME
        else
          echo "No CNAME file found in repository root"
        fi
    
    - name: Create root redirect if needed
      run: |
        # Ensure index.html is properly configured for root access
        if [ -f site/index.html ]; then
          echo "index.html found in site directory"
        else
          echo "Warning: No index.html found!"
        fi
    
    - name: Setup Pages
      if: github.ref == 'refs/heads/main'
      uses: actions/configure-pages@v4
    
    - name: Upload Pages artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./site
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      id: deployment
      uses: actions/deploy-pages@v4